nombre_completo = str(input("Ingresa tú nombre completo >> "))
nU = nombre_completo.upper()
nL = nombre_completo.lower()
nT = nombre_completo.title()
print(f"Nombre completo con todo mayúsculas {nU} y con todo minúsculas {nL} y con la primera letra mayuscula {nT}")